version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8002:10000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0a4q4pr0fns73ea995g-a.singapore-postgres.render.com:5432/recipe_5g0j
      SPRING_DATASOURCE_USERNAME: recipe_5g0j_user
      SPRING_DATASOURCE_PASSWORD: 0NVkH8p7G9uSkmEnOaNx1CCre2ZM75qF
      SERVER_PORT: 10000